name: CONTINUOUS DELIVERY AND DEPLOYMENT

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login In To Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build The Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            abdullah00001/workly-contacts-client:${{github.ref_name}}
            abdullah00001/workly-contacts-client:latest
        # run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
      # - name: Deploy to Render
